enum Keys{
    ArrowUp = "ArrowUp",
    ArrowDown = "ArrowDown",
    ArrowLeft = "ArrowLeft",
    ArrowRight = "ArrowRight",
    Shift = "Shift",
    Control = "Control",    
    Alt = "Alt",
    Meta = "Meta",
    Tab = "Tab",
    CapsLock = "CapsLock",
    F1 = "F1",
    F2 = "F2",
    F3 = "F3",
    F4 = "F4",
    F5 = "F5",
    F6 = "F6",
    F7 = "F7",
    F8 = "F8",
    F9 = "F9",
    F10 = "F10",
    F11 = "F11",
    F12 = "F12",
    Backspace = "Backspace",
    Num1 = "1",
    Num2 = "2",
    Num3 = "3",
    Num4 = "4",
    Num5 = "5",
    Num6 = "6",
    Num7 = "7",
    Num8 = "8",
    Num9 = "9",
    Num0 = "0",
    Minus = "-",
    Plus = "+",
    Equal = "=",
    Comma = ",",
    Dot = ".",
    Slash = "/",
    Backslack = "\\",
    BracketOpen = "{",
    BracketClose = "}",
    Enter = "Enter",
    Space = " ",
    A = "a",
    B = "b",
    C = "c",
    D = "d",
    E = "e",
    F = "f",
    G = "g",
    H = "h",
    I = "i",
    J = "j",
    K = "k",
    L = "l",
    M = "m",
    N = "n",
    O = "o",
    P = "p",
    Q = "q",
    R = "r",
    S = "s",
    T = "t",
    U = "u",
    V = "v",
    W = "w",
    X = "x",
    Y = "y",
    Z = "z",




}

export default Keys;